// Chronicle: Mock data for development and fallback
import { WorldState, City, TradeRoute, Region } from './types';

// Initial world state at 10,000 BC
export const MOCK_WORLD_STATE_10000BC: WorldState = {
  year: -10000,
  epoch: 1,
  narrative: "The Ice Age is ending. Small bands of humans are scattered across the continents, beginning to experiment with agriculture in the Fertile Crescent. The first permanent settlements are emerging where wild grains grow abundantly.",
  cities: [
    {
      id: "jericho",
      name: "Proto-Jericho",
      lat: 31.87,
      lng: 35.44,
      population: 300,
      brightness: 0.3,
      techLevel: 2,
      civilization: "Natufian",
      description: "One of the earliest permanent settlements. Hunter-gatherers are beginning to cultivate wild wheat and barley.",
    },
    {
      id: "gobekli",
      name: "Göbekli Tepe",
      lat: 37.22,
      lng: 38.92,
      population: 200,
      brightness: 0.4,
      techLevel: 2,
      civilization: "Pre-Pottery Neolithic",
      description: "A mysterious ceremonial site where massive stone pillars are being erected. The first known monumental architecture.",
    },
    {
      id: "catalhoyuk",
      name: "Proto-Çatalhöyük",
      lat: 37.67,
      lng: 32.83,
      population: 150,
      brightness: 0.2,
      techLevel: 2,
      civilization: "Anatolian",
      description: "Early farming communities in the Anatolian highlands, experimenting with domesticated crops.",
    },
    {
      id: "mehrgarh",
      name: "Mehrgarh",
      lat: 29.38,
      lng: 67.54,
      population: 100,
      brightness: 0.2,
      techLevel: 1,
      civilization: "Indus Precursor",
      description: "One of the earliest farming villages in South Asia, cultivating wheat and barley.",
    },
    {
      id: "hemudu",
      name: "Hemudu Culture",
      lat: 30.05,
      lng: 121.35,
      population: 80,
      brightness: 0.2,
      techLevel: 1,
      civilization: "Yangtze",
      description: "Early rice cultivation communities along the Yangtze River.",
    },
    {
      id: "nile_delta",
      name: "Nile Settlements",
      lat: 30.04,
      lng: 31.23,
      population: 120,
      brightness: 0.2,
      techLevel: 1,
      civilization: "Proto-Egyptian",
      description: "Scattered fishing and farming communities along the fertile Nile floodplain.",
    },
    {
      id: "zagros",
      name: "Zagros Foothills",
      lat: 35.5,
      lng: 46.0,
      population: 180,
      brightness: 0.25,
      techLevel: 2,
      civilization: "Proto-Sumerian",
      description: "Goat and sheep herders are beginning to settle, laying foundations for Mesopotamian civilization.",
    },
    {
      id: "ubaid",
      name: "Proto-Ubaid",
      lat: 30.96,
      lng: 46.10,
      population: 100,
      brightness: 0.2,
      techLevel: 1,
      civilization: "Mesopotamian",
      description: "Early communities in the marshlands between the Tigris and Euphrates rivers.",
    },
    {
      id: "sahara",
      name: "Green Sahara Camps",
      lat: 23.0,
      lng: 12.0,
      population: 60,
      brightness: 0.15,
      techLevel: 1,
      civilization: "Saharan",
      description: "The Sahara is still green. Pastoral communities herd cattle across the grasslands.",
    },
    {
      id: "baltic",
      name: "Baltic Hunter Camps",
      lat: 55.0,
      lng: 23.0,
      population: 40,
      brightness: 0.1,
      techLevel: 1,
      civilization: "Mesolithic European",
      description: "Hunter-gatherer bands following reindeer herds as the ice retreats.",
    },
    {
      id: "doggerland",
      name: "Doggerland",
      lat: 54.0,
      lng: 2.0,
      population: 50,
      brightness: 0.1,
      techLevel: 1,
      civilization: "Mesolithic European",
      description: "A land bridge between Britain and Europe, soon to be flooded by rising seas.",
    },
    {
      id: "clovis",
      name: "Clovis Culture",
      lat: 34.4,
      lng: -103.2,
      population: 30,
      brightness: 0.1,
      techLevel: 1,
      civilization: "Paleo-American",
      description: "Big-game hunters spreading across North America, hunting mammoth and bison.",
    },
    {
      id: "peru_coast",
      name: "Peruvian Coast",
      lat: -12.0,
      lng: -77.0,
      population: 40,
      brightness: 0.1,
      techLevel: 1,
      civilization: "Andean Precursor",
      description: "Fishing communities along the Pacific coast, beginning to settle permanently.",
    },
    {
      id: "jomon",
      name: "Jōmon Japan",
      lat: 35.7,
      lng: 139.7,
      population: 50,
      brightness: 0.15,
      techLevel: 1,
      civilization: "Jōmon",
      description: "Sophisticated hunter-gatherers creating the world's oldest pottery.",
    },
    {
      id: "australia",
      name: "Arnhem Land",
      lat: -12.5,
      lng: 133.0,
      population: 30,
      brightness: 0.1,
      techLevel: 1,
      civilization: "Aboriginal",
      description: "Ancient rock art traditions continue. Complex songlines map the continent.",
    },
  ],
  tradeRoutes: [
    {
      id: "fertile_crescent_1",
      from: { lat: 31.87, lng: 35.44, city: "Proto-Jericho" },
      to: { lat: 37.22, lng: 38.92, city: "Göbekli Tepe" },
      volume: 2,
      description: "Obsidian and grain exchange along the Fertile Crescent",
    },
    {
      id: "fertile_crescent_2",
      from: { lat: 37.22, lng: 38.92, city: "Göbekli Tepe" },
      to: { lat: 35.5, lng: 46.0, city: "Zagros Foothills" },
      volume: 1,
      description: "Early pastoral connections across Anatolia",
    },
    {
      id: "nile_levant",
      from: { lat: 30.04, lng: 31.23, city: "Nile Settlements" },
      to: { lat: 31.87, lng: 35.44, city: "Proto-Jericho" },
      volume: 1,
      description: "Shells and grain moving between Egypt and the Levant",
    },
  ],
  regions: [
    {
      id: "fertile_crescent",
      civilization: "Natufian / Pre-Pottery Neolithic",
      color: "#8B4513",
      center: { lat: 34.0, lng: 38.0 },
      radius: 8,
    },
    {
      id: "nile_valley",
      civilization: "Proto-Egyptian",
      color: "#CD853F",
      center: { lat: 26.0, lng: 32.0 },
      radius: 5,
    },
    {
      id: "indus_region",
      civilization: "Indus Precursor",
      color: "#D2691E",
      center: { lat: 28.0, lng: 70.0 },
      radius: 4,
    },
    {
      id: "yellow_river",
      civilization: "Yangtze / Yellow River",
      color: "#DAA520",
      center: { lat: 34.0, lng: 110.0 },
      radius: 6,
    },
    {
      id: "europe",
      civilization: "Mesolithic European",
      color: "#556B2F",
      center: { lat: 48.0, lng: 10.0 },
      radius: 10,
    },
  ],
};

// Sample world state at 2000 BC for testing
export const MOCK_WORLD_STATE_2000BC: WorldState = {
  year: -2000,
  epoch: 2,
  narrative: "Bronze Age civilizations flourish around the Mediterranean, in Egypt, Mesopotamia, and the Indus Valley. Writing has been invented. The first empires are forming. Trade networks span thousands of miles.",
  cities: [
    {
      id: "ur",
      name: "Ur",
      lat: 30.96,
      lng: 46.10,
      population: 65000,
      brightness: 0.9,
      techLevel: 5,
      civilization: "Sumerian",
      description: "One of the world's largest cities. Center of trade, religion, and the arts. Home to the great ziggurat.",
    },
    {
      id: "babylon",
      name: "Babylon",
      lat: 32.54,
      lng: 44.42,
      population: 40000,
      brightness: 0.8,
      techLevel: 5,
      civilization: "Babylonian",
      description: "Rising power in Mesopotamia. Will soon eclipse Ur as the dominant city.",
    },
    {
      id: "memphis",
      name: "Memphis",
      lat: 29.85,
      lng: 31.25,
      population: 50000,
      brightness: 0.85,
      techLevel: 5,
      civilization: "Egyptian",
      description: "Capital of unified Egypt. The pyramids stand as monuments to divine pharaonic power.",
    },
    {
      id: "thebes",
      name: "Thebes",
      lat: 25.70,
      lng: 32.64,
      population: 30000,
      brightness: 0.7,
      techLevel: 5,
      civilization: "Egyptian",
      description: "Religious center of Egypt. Temple complexes honor Amun-Ra.",
    },
    {
      id: "knossos",
      name: "Knossos",
      lat: 35.30,
      lng: 25.16,
      population: 20000,
      brightness: 0.75,
      techLevel: 5,
      civilization: "Minoan",
      description: "Heart of Minoan civilization. The labyrinthine palace amazes visitors.",
    },
    {
      id: "mohenjo_daro",
      name: "Mohenjo-daro",
      lat: 27.33,
      lng: 68.14,
      population: 40000,
      brightness: 0.8,
      techLevel: 5,
      civilization: "Indus Valley",
      description: "Masterwork of urban planning. Grid streets, sewage systems, public baths.",
    },
    {
      id: "harappa",
      name: "Harappa",
      lat: 30.63,
      lng: 72.87,
      population: 35000,
      brightness: 0.75,
      techLevel: 5,
      civilization: "Indus Valley",
      description: "Twin city to Mohenjo-daro. Center of the northern Indus trade network.",
    },
    {
      id: "anyang",
      name: "Erlitou",
      lat: 34.70,
      lng: 112.70,
      population: 25000,
      brightness: 0.6,
      techLevel: 4,
      civilization: "Xia Dynasty",
      description: "Legendary first dynasty of China. Bronze casting is advancing rapidly.",
    },
    {
      id: "troy",
      name: "Troy",
      lat: 39.96,
      lng: 26.24,
      population: 8000,
      brightness: 0.5,
      techLevel: 4,
      civilization: "Anatolian",
      description: "Strategic fortress controlling the Dardanelles. Rich from trade tolls.",
    },
    {
      id: "ugarit",
      name: "Ugarit",
      lat: 35.60,
      lng: 35.78,
      population: 15000,
      brightness: 0.6,
      techLevel: 4,
      civilization: "Canaanite",
      description: "Cosmopolitan port city. Multiple languages and scripts in daily use.",
    },
  ],
  tradeRoutes: [
    {
      id: "mesopotamia_egypt",
      from: { lat: 30.96, lng: 46.10, city: "Ur" },
      to: { lat: 29.85, lng: 31.25, city: "Memphis" },
      volume: 8,
      description: "Luxury goods, copper, and grain flow between the great river civilizations",
    },
    {
      id: "minoan_egypt",
      from: { lat: 35.30, lng: 25.16, city: "Knossos" },
      to: { lat: 29.85, lng: 31.25, city: "Memphis" },
      volume: 6,
      description: "Minoan ships carry olive oil, wine, and crafts to Egypt",
    },
    {
      id: "indus_mesopotamia",
      from: { lat: 27.33, lng: 68.14, city: "Mohenjo-daro" },
      to: { lat: 30.96, lng: 46.10, city: "Ur" },
      volume: 5,
      description: "Sea trade via the Persian Gulf. Carnelian beads, cotton, ivory",
    },
    {
      id: "minoan_troy",
      from: { lat: 35.30, lng: 25.16, city: "Knossos" },
      to: { lat: 39.96, lng: 26.24, city: "Troy" },
      volume: 4,
      description: "Aegean trade network. Metals from the Black Sea region",
    },
    {
      id: "levant_trade",
      from: { lat: 35.60, lng: 35.78, city: "Ugarit" },
      to: { lat: 32.54, lng: 44.42, city: "Babylon" },
      volume: 5,
      description: "Cedar wood, purple dye, and crafts from the Levantine coast",
    },
  ],
  regions: [
    {
      id: "mesopotamia",
      civilization: "Sumerian / Babylonian",
      color: "#4169E1",
      center: { lat: 32.0, lng: 45.0 },
      radius: 6,
    },
    {
      id: "egypt",
      civilization: "Egyptian New Kingdom",
      color: "#FFD700",
      center: { lat: 27.0, lng: 31.0 },
      radius: 5,
    },
    {
      id: "minoan",
      civilization: "Minoan",
      color: "#8A2BE2",
      center: { lat: 36.0, lng: 25.0 },
      radius: 4,
    },
    {
      id: "indus",
      civilization: "Indus Valley",
      color: "#20B2AA",
      center: { lat: 28.0, lng: 70.0 },
      radius: 5,
    },
    {
      id: "shang",
      civilization: "Xia / Early Shang",
      color: "#DC143C",
      center: { lat: 35.0, lng: 113.0 },
      radius: 6,
    },
  ],
};
